version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: weather_service_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: weather_service_redis
    restart: always
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  weather-service:
    build: ./weather-service
    container_name: weather_service
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      WEATHER_API_KEY: ${WEATHER_API_KEY}
      RABBITMQ_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    ports:
      - "3002:3002"

  email-service:
    build: ./email-service
    container_name: email_service
    environment:
      EMAIL_API_KEY: ${EMAIL_API_KEY}
      EMAIL_SENDER: ${EMAIL_SENDER}
      RABBITMQ_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    ports:
      - "3001:3001"

  subscription-service:
    build: ./subscription-service
    container_name: subscription_service
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
    ports:
      - "3003:3003"

  notification-service:
    build: ./notification-service
    container_name: notification_service
    depends_on:
      - rabbitmq
      - email-service
    environment:
      RABBITMQ_URL: amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@rabbitmq:5672
    ports:
      - "3004:3004"

  api-gateway:
    build: ./api-gateway
    container_name: api_gateway
    depends_on:
      - weather-service
      - email-service
      - subscription-service
    environment:
      WEATHER_SERVICE_URL: http://weather-service:3002
      EMAIL_SERVICE_URL: http://email-service:3001
      SUBSCRIPTION_SERVICE_URL: http://subscription-service:3003
    ports:
      - "3000:3000"

volumes:
  pgdata:
